# ТЕСТОВОЕ ЗАДАНИЕ

Есть два файла, src_survey и src_OnOff. 
В таблице src_survey результат опроса респондентов - участников исследования, целью которого является проверка работы оборудования и регистрации респондентов на пиплметре (измерительное устройство для фиксации телесмотрения). 

В рамках каждой процедуры в одном домохозяйстве (ДХ) проверяется, кто из респондентов находится в комнате с включенным телевизором. В ДХ может быть несколько приборов (телевизоров), могут проживать несколько респондентов. В опросе содержится информация по каждому телевизору и каждому респонденту. Далее, результат опроса сравнивается с данными регистрации респондента на пиплметре во время опроса, результат сравнения фиксируется в таблице (см. описание полей)   
Нужно проанализировать:

1.	Количество ситуаций (абс, %), когда прибор фактически выключен (данные в таблице src_OnOff), а респондент утверждает, что включен


2.	Количество ситуаций (абс, %), когда прибор фактически включен (данные в таблице src_OnOff), а респондент утверждает, что выключен


3.	Выделить ДХ с размером более 1 человека, среди них ситуации, телевизор фактически включен, респондент по данным опроса находится в комнате с включенным телевизором, регистрации нет, а у других респондентов в этом ДХ регистрация на этом телевизоре есть. Необходимо сгруппировать результат в зависимости от размера ДХ. \

Описание полей:
●	статус телевизора по утверждению респондента: tv state

●	размер ДХ: Кол-во человек в семье 4+

●	наличие фактической регистрации на пиплметре: see

●	наличие респондента в комнате с телевизором согласно опросу: display 

●	идентификатор ДХ: passport (PassportNumber в таблице src_OnOff)

●	фактический статус телевизора: DeviceState (ON включен, OFF выключен)

●	идентификатор респондента: button

●	идентификатор телевизора: unit (UnitNumber в таблице src_OnOff)

Мы ждем:

1.	Скрипт Python

2.	Результат анализа (данные + небольшой аналитический комментарий)


# Предобработка данных
## Общая информация

In [1]:
import pandas as pd
from datetime import datetime, timedelta
import datetime as dt

In [2]:
survey = pd.read_excel('C:\\Users\\K\\Test/src_survey.xlsx')
survey 

code  passport button  tv state  unit                  day  cs_start  \
0    258104   1204558      А  выключен     0             07.02.22  16:25:18   
1    258106   1205697      Б   включён     0             07.02.22  16:50:18   
2    258106   1205697      А   включён     0             07.02.22  16:50:18   
3    258106   1205697      В   включён     0             07.02.22  16:50:18   
4    258109   1206994      А  выключен     1  2022-02-08 00:00:00  03:05:31   
..      ...       ...    ...       ...   ...                  ...       ...   
202  258546   1212330      А   включён     0             14.02.22  18:44:21   
203  258546   1212330      Б   включён     0             14.02.22  18:44:21   
204  258546   1212330      Д   включён     0             14.02.22  18:44:21   
205  258548   1212873      А   включён     0             14.02.22  19:24:42   
206  258552   1212916      А   включён     0             14.02.22  19:39:23   

    cs_finish               see        display  Кол-во человек в семье 4+  
0    16:26:09   нет регистрации  нет в комнате                          1  
1    16:53:17   нет регистрации      в комнате                          3  
2    16:53:17   нет регистрации  нет в комнате                          3  
3    16:53:17   нет регистрации      в комнате                          3  
4    03:06:58   нет регистрации  нет в комнате                          1  
..        ...               ...            ...                        ...  
202  18:46:04   нет регистрации  нет в комнате                          4  
203  18:46:04   нет регистрации  нет в комнате                          4  
204  18:46:04  есть регистрация      в комнате                          4  
205  19:26:55  есть регистрация      в комнате                          1  
206  19:41:36  есть регистрация      в комнате                          1  

[207 rows x 11 columns]

In [3]:
data_on_off = pd.read_excel('C:\\Users\\K\\Test/src_OnOff.xlsx')
data_on_off

PassportNumber  UnitNumber DeviceState                    Begin  \
0             10100003           0         OFF  2022-02-07 02:00:00.000   
1             10100003           0         OFF  2022-02-08 02:00:00.000   
2             10100003           0          ON  2022-02-08 11:48:42.000   
3             10100003           0         OFF  2022-02-08 12:36:55.000   
4             10100003           0          ON  2022-02-08 22:05:17.000   
...                ...         ...         ...                      ...   
642129          502286           0         OFF  2022-02-15 20:16:01.000   
642130          502286           0          ON  2022-02-15 20:53:31.000   
642131          502286           0         OFF  2022-02-15 21:43:15.000   
642132          502286           0          ON  2022-02-15 22:09:59.000   
642133          502286           0         OFF  2022-02-15 22:19:33.000   

                            End  
0       2022-02-08 02:00:00.000  
1       2022-02-08 11:48:42.000  
2       2022-02-08 12:36:55.000  
3       2022-02-08 22:05:17.000  
4       2022-02-08 23:48:03.000  
...                         ...  
642129  2022-02-15 20:53:31.000  
642130  2022-02-15 21:43:15.000  
642131  2022-02-15 22:09:59.000  
642132  2022-02-15 22:19:33.000  
642133  2022-02-16 02:00:00.000  

[642134 rows x 5 columns]

In [4]:
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 11 columns):
 #   Column                     Non-Null Count  Dtype 
---  ------                     --------------  ----- 
 0   code                       207 non-null    int64 
 1   passport                   207 non-null    int64 
 2   button                     207 non-null    object
 3   tv state                   207 non-null    object
 4   unit                       207 non-null    int64 
 5   day                        207 non-null    object
 6   cs_start                   207 non-null    object
 7   cs_finish                  207 non-null    object
 8   see                        207 non-null    object
 9   display                    207 non-null    object
 10  Кол-во человек в семье 4+  207 non-null    int64 
dtypes: int64(4), object(7)
memory usage: 17.9+ KB


In [5]:
data_on_off.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642134 entries, 0 to 642133
Data columns (total 5 columns):
 #   Column          Non-Null Count   Dtype 
---  ------          --------------   ----- 
 0   PassportNumber  642134 non-null  int64 
 1   UnitNumber      642134 non-null  int64 
 2   DeviceState     642134 non-null  object
 3   Begin           642134 non-null  object
 4   End             642134 non-null  object
dtypes: int64(2), object(3)
memory usage: 24.5+ MB


У нас есть таблица **survey**, описывающая результат опроса респондентов. И таблица **data_on_off** с информацией о том, включен ли фактически прибор. 
По предварительному осмотру видим, что пропущенных значений нет, названия столбцов не соответствуют хорошему стилю, не все столбцы имеют подходящий тип данных.

## Предобработка данных

In [6]:
# Уберем пробелы, заглавные буквы, кириллицу из названий столбцов
data_on_off.columns = [x.lower().replace('number' , '_number').replace('state' , '_state') for x in data_on_off.columns]

In [7]:
survey = survey.rename(columns = {'passport':'passport_number', 'unit':'unit_number', 'tv state':'tv_state',\
                                  'Кол-во человек в семье 4+':'people_cnt'})

In [8]:
# Приведём столбцы с датой в формат datetime
data_on_off['begin'] = pd.to_datetime(data_on_off['begin'])
data_on_off['end'] = pd.to_datetime(data_on_off['end'])

In [9]:
# Добавим столбцы, содержащие сразу дату и время, приведем их в формат datetime 
survey['day'] = pd.to_datetime(survey['day'])

survey['day'] = survey['day'].astype('str')
survey['cs_start'] = survey['cs_start'].astype('str')
survey['cs_finish'] = survey['cs_finish'].astype('str')

survey['survey_start'] = survey['day'] + ' ' + survey['cs_start']
survey['survey_finish'] = survey['day'] + ' ' + survey['cs_finish']
del survey['day'], survey['cs_start'], survey['cs_finish']

In [10]:
survey['survey_start'] = pd.to_datetime(survey['survey_start'])
survey['survey_finish'] = pd.to_datetime(survey['survey_finish'])


In [11]:
# Убедимся, что изменения внесены корректно
data_on_off.info()
survey.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 642134 entries, 0 to 642133
Data columns (total 5 columns):
 #   Column           Non-Null Count   Dtype         
---  ------           --------------   -----         
 0   passport_number  642134 non-null  int64         
 1   unit_number      642134 non-null  int64         
 2   device_state     642134 non-null  object        
 3   begin            642134 non-null  datetime64[ns]
 4   end              642134 non-null  datetime64[ns]
dtypes: datetime64[ns](2), int64(2), object(1)
memory usage: 24.5+ MB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 207 entries, 0 to 206
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype         
---  ------           --------------  -----         
 0   code             207 non-null    int64         
 1   passport_number  207 non-null    int64         
 2   button           207 non-null    object        
 3   tv_state         207 non-null    object        
 4   unit_number   

In [12]:
# Проверяем наличие явных дубликатов в датафреймах
print(survey.duplicated().sum())
print(data_on_off.duplicated().sum())

0
0


In [13]:
# Посмотрим, какие значения представлены в некоторых столбцах
survey['tv_state'].unique()

array(['выключен', 'включён'], dtype=object)

In [14]:
survey['display'].unique()

array(['нет в комнате', 'в комнате'], dtype=object)

In [15]:
survey['see'].unique()

array(['нет регистрации', 'есть регистрация'], dtype=object)

In [16]:
data_on_off['device_state'].unique()

array(['OFF', 'ON', 'D', 'U'], dtype=object)

Видим, что помимо заданных ON и OFF, встречаются значения D и U. Посмотрим, сколько строк с такими значениями. 

In [17]:
print(data_on_off[data_on_off['device_state'] == 'D'])
data_on_off[data_on_off['device_state'] == 'U']

        passport_number  unit_number device_state               begin  \
1543           10100151            0            D 2022-02-13 14:17:22   
1545           10100151            0            D 2022-02-13 14:24:14   
1547           10100151            0            D 2022-02-13 15:23:34   
1549           10100151            0            D 2022-02-13 15:43:47   
1551           10100151            0            D 2022-02-13 15:45:40   
...                 ...          ...          ...                 ...   
641919           502260            1            D 2022-02-11 10:53:03   
641921           502260            1            D 2022-02-11 13:29:13   
641924           502260            1            D 2022-02-11 13:46:37   
641927           502260            1            D 2022-02-11 13:57:27   
641930           502260            1            D 2022-02-11 14:02:26   

                       end  
1543   2022-02-13 14:17:26  
1545   2022-02-13 15:23:03  
1547   2022-02-13 15:42:00  
1549   

passport_number  unit_number device_state               begin  \
49445          10300408            0            U 2022-02-11 02:00:00   
69372          14600218            0            U 2022-02-14 02:00:00   
73048          14600475            1            U 2022-02-13 02:00:00   
75552          14600626            1            U 2022-02-15 02:00:00   
76632          14600729            0            U 2022-02-12 02:00:00   
112026         18200029            0            U 2022-02-11 02:00:00   
115155         18500048            1            U 2022-02-08 02:00:00   
135900         13600073            2            U 2022-02-09 02:00:00   
135941         13600073            1            U 2022-02-09 02:00:00   
135949         13600073            0            U 2022-02-09 02:00:00   
158323         16900023            0            U 2022-02-09 02:00:00   
160347         17000064            2            U 2022-02-13 02:00:00   
160825         17000101            0            U 2022-02-13 02:00:00   
168304         17500042            1            U 2022-02-14 02:00:00   
185364          5200537            2            U 2022-02-13 02:00:00   
185365          5200537            2            U 2022-02-14 02:00:00   
200985          6100460            0            U 2022-02-12 02:00:00   
208478          4901941            1            U 2022-02-12 02:00:00   
208525          4901941            0            U 2022-02-12 02:00:00   
208552          4901941            2            U 2022-02-12 02:00:00   
225238          7900357            0            U 2022-02-07 02:00:00   
235955          2600349            0            U 2022-02-13 02:00:00   
271820          1100937            0            U 2022-02-11 02:00:00   
283596          2102435            0            U 2022-02-13 02:00:00   
287374          5101247            1            U 2022-02-07 02:00:00   
287375          5101247            1            U 2022-02-08 02:00:00   
324247          1205907            0            U 2022-02-09 02:00:00   
372274          1211318            4            U 2022-02-07 02:00:00   
372484          1211321            1            U 2022-02-11 02:00:00   
382860          1212067            2            U 2022-02-09 02:00:00   
382909          1212067            1            U 2022-02-09 02:00:00   
453784          6500257            0            U 2022-02-07 02:00:00   
470927          1500793            1            U 2022-02-08 02:00:00   
470928          1500793            1            U 2022-02-09 02:00:00   
475068          1501120            0            U 2022-02-11 02:00:00   
482460          4000422            0            U 2022-02-13 02:00:00   
497071          4100574            1            U 2022-02-14 02:00:00   
531397           104094            0            U 2022-02-10 02:00:00   
565498          4400163            0            U 2022-02-11 02:00:00   
565499          4400163            0            U 2022-02-12 02:00:00   
584868          6001449            1            U 2022-02-11 02:00:00   
584913          6001449            0            U 2022-02-11 02:00:00   
588640          1800520            1            U 2022-02-10 02:00:00   
588641          1800520            1            U 2022-02-11 02:00:00   
595804          7800235            1            U 2022-02-08 02:00:00   
595805          7800235            1            U 2022-02-09 02:00:00   
596004          7800235            0            U 2022-02-08 02:00:00   
596005          7800235            0            U 2022-02-09 02:00:00   
631141          1604282            0            U 2022-02-14 02:00:00   
631142          1604282            0            U 2022-02-15 02:00:00   
632867          6800076            0            U 2022-02-12 02:00:00   

                       end  
49445  2022-02-11 09:04:04  
69372  2022-02-14 16:43:27  
73048  2022-02-13 14:53:59  
75552  2022-02-16 02:00:00  
76632  2022-02-12 18:13:14  
112026 2022-02-11 11:37:56  
115155 2

Таких строк около 700. Для таблицы с более чем 600000 строками это совсем небольшое количество. Будем считать, что выяснить, что обозначают D и U, нет возможности. Пока удалять не будем, посмотрим, сколько останется таких строк после слияния таблиц.

In [18]:
# Объединим таблицы, оставив данные только по тем ДХ, которые участвовали в опросе. Так же учитываем идентификатор телевизора.
survey_real = survey.merge(data_on_off, on=['passport_number', 'unit_number'], how='left')
survey_real

code  passport_number button  tv_state  unit_number               see  \
0     258104          1204558      А  выключен            0   нет регистрации   
1     258104          1204558      А  выключен            0   нет регистрации   
2     258104          1204558      А  выключен            0   нет регистрации   
3     258104          1204558      А  выключен            0   нет регистрации   
4     258104          1204558      А  выключен            0   нет регистрации   
...      ...              ...    ...       ...          ...               ...   
9269  258552          1212916      А   включён            0  есть регистрация   
9270  258552          1212916      А   включён            0  есть регистрация   
9271  258552          1212916      А   включён            0  есть регистрация   
9272  258552          1212916      А   включён            0  есть регистрация   
9273  258552          1212916      А   включён            0  есть регистрация   

            display  people_cnt        survey_start       survey_finish  \
0     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
1     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
2     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
3     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
4     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
...             ...         ...                 ...                 ...   
9269      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9270      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9271      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9272      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9273      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   

     device_state               begin                 end  
0             OFF 2022-02-07 02:00:00 2022-02-07 17:17:45  
1              ON 2022-02-07 17:17:45 2022-02-07 21:46:30  
2             OFF 2022-02-07 21:46:30 2022-02-08 02:00:00  
3             OFF 2022-02-08 02:00:00 2022-02-08 16:39:15  
4              ON 2022-02-08 16:39:15 2022-02-08 21:13:21  
...           ...                 ...                 ...  
9269          OFF 2022-02-15 01:21:06 2022-02-15 02:00:00  
9270          OFF 2022-02-15 02:00:00 2022-02-15 02:49:55  
9271           ON 2022-02-15 02:49:55 2022-02-15 10:04:29  
9272          OFF 2022-02-15 10:04:29 2022-02-15 16:26:17  
9273           ON 2022-02-15 16:26:17 2022-02-16 02:00:00  

[9274 rows x 13 columns]

In [19]:
# Посмотрим, сколько осталось строк с непонятными значениями в device_state
print(survey_real[survey_real['device_state'] == 'D'])
survey_real[survey_real['device_state'] == 'U']

        code  passport_number button  tv_state  unit_number              see  \
4821  258513          1206092      Б  выключен            0  нет регистрации   
4823  258513          1206092      Б  выключен            0  нет регистрации   
5179  258520          1208602      Б  выключен            2  нет регистрации   
5283  258520          1208602      В  выключен            2  нет регистрации   
5387  258520          1208602      Г  выключен            2  нет регистрации   
8247  258541          1211033      А  выключен            0  нет регистрации   
8367  258541          1211033      Б  выключен            0  нет регистрации   
8487  258541          1211033      В  выключен            0  нет регистрации   

            display  people_cnt        survey_start       survey_finish  \
4821  нет в комнате           2 2022-02-14 17:50:31 2022-02-14 17:52:23   
4823  нет в комнате           2 2022-02-14 17:50:31 2022-02-14 17:52:23   
5179  нет в комнате           3 2022-02-14 19:33:49 20

Empty DataFrame
Columns: [code, passport_number, button, tv_state, unit_number, see, display, people_cnt, survey_start, survey_finish, device_state, begin, end]
Index: []

Осталось всего 8 строк с записью 'D' в столбце 'device_state'. Просто удалим их.

In [20]:
survey_real = survey_real[survey_real['device_state'] != 'D']
survey_real

code  passport_number button  tv_state  unit_number               see  \
0     258104          1204558      А  выключен            0   нет регистрации   
1     258104          1204558      А  выключен            0   нет регистрации   
2     258104          1204558      А  выключен            0   нет регистрации   
3     258104          1204558      А  выключен            0   нет регистрации   
4     258104          1204558      А  выключен            0   нет регистрации   
...      ...              ...    ...       ...          ...               ...   
9269  258552          1212916      А   включён            0  есть регистрация   
9270  258552          1212916      А   включён            0  есть регистрация   
9271  258552          1212916      А   включён            0  есть регистрация   
9272  258552          1212916      А   включён            0  есть регистрация   
9273  258552          1212916      А   включён            0  есть регистрация   

            display  people_cnt        survey_start       survey_finish  \
0     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
1     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
2     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
3     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
4     нет в комнате           1 2022-07-02 16:25:18 2022-07-02 16:26:09   
...             ...         ...                 ...                 ...   
9269      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9270      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9271      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9272      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   
9273      в комнате           1 2022-02-14 19:39:23 2022-02-14 19:41:36   

     device_state               begin                 end  
0             OFF 2022-02-07 02:00:00 2022-02-07 17:17:45  
1              ON 2022-02-07 17:17:45 2022-02-07 21:46:30  
2             OFF 2022-02-07 21:46:30 2022-02-08 02:00:00  
3             OFF 2022-02-08 02:00:00 2022-02-08 16:39:15  
4              ON 2022-02-08 16:39:15 2022-02-08 21:13:21  
...           ...                 ...                 ...  
9269          OFF 2022-02-15 01:21:06 2022-02-15 02:00:00  
9270          OFF 2022-02-15 02:00:00 2022-02-15 02:49:55  
9271           ON 2022-02-15 02:49:55 2022-02-15 10:04:29  
9272          OFF 2022-02-15 10:04:29 2022-02-15 16:26:17  
9273           ON 2022-02-15 16:26:17 2022-02-16 02:00:00  

[9266 rows x 13 columns]

## Исследовательский анализ

### Количество ситуаций (абс, %), когда прибор фактически выключен (данные в таблице src_OnOff), а респондент утверждает, что включен

In [21]:
# Выдел
device_off = survey_real[((survey_real['device_state'] == 'OFF') & (survey_real['tv_state']  == 'включён'))\
                & ((survey_real['survey_start'] > survey_real['begin']) & (survey_real['survey_start'] < survey_real['end']))]\
                .reset_index(drop=True)
device_off

code  passport_number button tv_state  unit_number               see  \
0  258548          1212873      А  включён            0  есть регистрация   

     display  people_cnt        survey_start       survey_finish device_state  \
0  в комнате           1 2022-02-14 19:24:42 2022-02-14 19:26:55          OFF   

                begin                 end  
0 2022-02-14 02:00:00 2022-02-14 19:24:55

In [22]:
print('Общее количество ситуаций:', len(survey_real))
print('Количество ситуаций, когда прибор фактически выключен, а пользователь утверждает, что включен:', len(device_off))    
print(f'(% таких ситуаций от общего количества: {round(len(device_off) * 100 /len(survey_real), 2)}%)')

Общее количество ситуаций: 9266
Количество ситуаций, когда прибор фактически выключен, а пользователь утверждает, что включен: 1
(% таких ситуаций от общего количества: 0.01%)


**Вывод:** Найдена всего лишь одна ситуация, когда респондент утверждает, что телевизор включен, а он фактически выключен. Можно заметить, что через 13 секунд после начала опроса телевизор включили.
Таким образом, на основании опросов респондентов, можем считать, что при фактически выключенном телевизоре пиплметр работает корректно.

###	Количество ситуаций (абс, %), когда прибор фактически включен (данные в таблице src_OnOff), а респондент утверждает, что выключен

In [23]:
device_on = survey_real[((survey_real['device_state'] == 'ON') & (survey_real['tv_state']  == 'выключен'))\
                & ((survey_real['survey_start'] > survey_real['begin']) & (survey_real['survey_start'] < survey_real['end']))]\
                .reset_index()
device_on

index    code  passport_number button  tv_state  unit_number  \
0    167  258109          1206994      А  выключен            1   
1   5521  258521          1208646      А  выключен            0   
2   5643  258521          1208646      Б  выключен            0   

               see        display  people_cnt        survey_start  \
0  нет регистрации  нет в комнате           1 2022-02-08 03:05:31   
1  нет регистрации  нет в комнате           2 2022-02-14 19:43:33   
2  нет регистрации  нет в комнате           2 2022-02-14 19:43:33   

        survey_finish device_state               begin                 end  
0 2022-02-08 03:06:58           ON 2022-02-08 02:00:00 2022-02-09 02:00:00  
1 2022-02-14 19:45:31           ON 2022-02-14 19:35:18 2022-02-14 21:54:48  
2 2022-02-14 19:45:31           ON 2022-02-14 19:35:18 2022-02-14 21:54:48

In [24]:
print('Количество ситуаций, когда прибор фактически включен, а пользователь утверждает, что выключен:', len(device_on))    
print(f'(% таких ситуаций от общего количества: {round(len(device_on) * 100 /len(survey_real), 2)}%)')

Количество ситуаций, когда прибор фактически включен, а пользователь утверждает, что выключен: 3
(% таких ситуаций от общего количества: 0.03%)


**Вывод:** Найдено всего лишь 3 ситуации, когда респондент утверждает, что прибор выключен, а он фактически включён. 
Стоит отметить, что 2 случая можно расценивать как один, так как они произошли в рамках опроса одного домохозяйства.

Таким образом, количество несоответствий ничтожно мало, и мы можем считать, что при фактически включённом телевизоре пиплметр тоже работает корректно.

###	Выделить ДХ с размером более 1 человека, среди них ситуации, телевизор фактически включен, респондент по данным опроса находится в комнате с включенным телевизором, регистрации нет, а у других респондентов в этом ДХ регистрация на этом телевизоре есть. Необходимо сгруппировать результат в зависимости от размера ДХ. 

In [25]:
# Выделим ДХ с размером более 1 человека
data = survey_real[survey_real['people_cnt'] >1].reset_index(drop=True)
data

code  passport_number button tv_state  unit_number               see  \
0     258106          1205697      Б  включён            0   нет регистрации   
1     258106          1205697      Б  включён            0   нет регистрации   
2     258106          1205697      Б  включён            0   нет регистрации   
3     258106          1205697      Б  включён            0   нет регистрации   
4     258106          1205697      Б  включён            0   нет регистрации   
...      ...              ...    ...      ...          ...               ...   
8901  258546          1212330      Д  включён            0  есть регистрация   
8902  258546          1212330      Д  включён            0  есть регистрация   
8903  258546          1212330      Д  включён            0  есть регистрация   
8904  258546          1212330      Д  включён            0  есть регистрация   
8905  258546          1212330      Д  включён            0  есть регистрация   

        display  people_cnt        survey_start       survey_finish  \
0     в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
1     в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
2     в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
3     в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
4     в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
...         ...         ...                 ...                 ...   
8901  в комнате           4 2022-02-14 18:44:21 2022-02-14 18:46:04   
8902  в комнате           4 2022-02-14 18:44:21 2022-02-14 18:46:04   
8903  в комнате           4 2022-02-14 18:44:21 2022-02-14 18:46:04   
8904  в комнате           4 2022-02-14 18:44:21 2022-02-14 18:46:04   
8905  в комнате           4 2022-02-14 18:44:21 2022-02-14 18:46:04   

     device_state               begin                 end  
0             OFF 2022-02-07 02:00:00 2022-02-07 10:39:19  
1              ON 2022-02-07 10:39:19 2022-02-07 16:55:30  
2             OFF 2022-02-07 16:55:30 2022-02-07 16:55:34  
3              ON 2022-02-07 16:55:34 2022-02-07 23:59:02  
4             OFF 2022-02-07 23:59:02 2022-02-08 01:00:27  
...           ...                 ...                 ...  
8901          OFF 2022-02-15 02:00:00 2022-02-15 14:04:28  
8902           ON 2022-02-15 14:04:28 2022-02-15 20:44:58  
8903          OFF 2022-02-15 20:44:58 2022-02-15 22:15:46  
8904           ON 2022-02-15 22:15:46 2022-02-15 23:58:54  
8905          OFF 2022-02-15 23:58:54 2022-02-16 02:00:00  

[8906 rows x 13 columns]

In [26]:
# Далее выделим ситуации, когда телевизор включен, респондент по данным опроса в комнате с включенным телевизором,
# регистрации нет. Так мы выделим ДХ, которые потенциально могут подойти.
data_2 = data[(data['device_state'] == 'ON') & (data['display'] == 'в комнате')\
                & (data['tv_state'] == 'включён') & (data['see'] == 'нет регистрации')].reset_index(drop=True)
data_2

code  passport_number button tv_state  unit_number              see  \
0    258106          1205697      Б  включён            0  нет регистрации   
1    258106          1205697      Б  включён            0  нет регистрации   
2    258106          1205697      Б  включён            0  нет регистрации   
3    258106          1205697      Б  включён            0  нет регистрации   
4    258106          1205697      Б  включён            0  нет регистрации   
..      ...              ...    ...      ...          ...              ...   
110  258128          1210930      Б  включён            1  нет регистрации   
111  258128          1210930      Б  включён            1  нет регистрации   
112  258128          1210930      Б  включён            1  нет регистрации   
113  258128          1210930      Б  включён            1  нет регистрации   
114  258128          1210930      Б  включён            1  нет регистрации   

       display  people_cnt        survey_start       survey_finish  \
0    в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
1    в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
2    в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
3    в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
4    в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
..         ...         ...                 ...                 ...   
110  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
111  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
112  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
113  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
114  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   

    device_state               begin                 end  
0             ON 2022-02-07 10:39:19 2022-02-07 16:55:30  
1             ON 2022-02-07 16:55:34 2022-02-07 23:59:02  
2             ON 2022-02-08 01:00:27 2022-02-08 01:07:29  
3             ON 2022-02-08 08:52:46 2022-02-08 23:05:08  
4             ON 2022-02-09 11:11:03 2022-02-09 23:33:34  
..           ...                 ...                 ...  
110           ON 2022-02-11 20:24:24 2022-02-12 00:19:07  
111           ON 2022-02-13 17:24:44 2022-02-13 19:04:13  
112           ON 2022-02-13 19:04:21 2022-02-13 21:18:43  
113           ON 2022-02-15 14:42:32 2022-02-15 19:38:38  
114           ON 2022-02-15 19:57:20 2022-02-15 23:50:20  

[115 rows x 13 columns]

In [27]:
# Выведем список номеров ДХ, которые потенциально могут подойти.
data_x = data_2['passport_number'].unique()
data_x

array([1205697, 1208135, 1210425, 1210930], dtype=int64)

In [28]:
# Рассмотрим все ситуации в вышеуказанных ДХ
data_3 = data[(data['passport_number'] == 1205697) | (data['passport_number'] == 1208135)\
            | (data['passport_number'] == 1210425) | (data['passport_number'] == 1210930)].reset_index(drop=True)
data_3

code  passport_number button  tv_state  unit_number              see  \
0     258106          1205697      Б   включён            0  нет регистрации   
1     258106          1205697      Б   включён            0  нет регистрации   
2     258106          1205697      Б   включён            0  нет регистрации   
3     258106          1205697      Б   включён            0  нет регистрации   
4     258106          1205697      Б   включён            0  нет регистрации   
...      ...              ...    ...       ...          ...              ...   
1042  258128          1210930      Г  выключен            0  нет регистрации   
1043  258128          1210930      Г  выключен            0  нет регистрации   
1044  258128          1210930      Г  выключен            0  нет регистрации   
1045  258128          1210930      Г  выключен            0  нет регистрации   
1046  258128          1210930      Г  выключен            0  нет регистрации   

            display  people_cnt        survey_start       survey_finish  \
0         в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
1         в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
2         в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
3         в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
4         в комнате           3 2022-07-02 16:50:18 2022-07-02 16:53:17   
...             ...         ...                 ...                 ...   
1042  нет в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
1043  нет в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
1044  нет в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
1045  нет в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
1046  нет в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   

     device_state               begin                 end  
0             OFF 2022-02-07 02:00:00 2022-02-07 10:39:19  
1              ON 2022-02-07 10:39:19 2022-02-07 16:55:30  
2             OFF 2022-02-07 16:55:30 2022-02-07 16:55:34  
3              ON 2022-02-07 16:55:34 2022-02-07 23:59:02  
4             OFF 2022-02-07 23:59:02 2022-02-08 01:00:27  
...           ...                 ...                 ...  
1042          OFF 2022-02-13 22:50:33 2022-02-14 02:00:00  
1043          OFF 2022-02-14 02:00:00 2022-02-15 02:00:00  
1044          OFF 2022-02-15 02:00:00 2022-02-15 07:50:46  
1045           ON 2022-02-15 07:50:46 2022-02-15 08:34:16  
1046          OFF 2022-02-15 08:34:16 2022-02-16 02:00:00  

[1047 rows x 13 columns]

In [29]:
# Выделим ДХ, в которых одновременно есть респонденты и с регистрацией, и без. 
# Т.е. сгруппировав данные по ДХ и телевизору, смотрим когда уникальных значений в столбце see больше, чем одно.
data_4 = data_3.groupby(['passport_number', 'unit_number']).agg({'see':'nunique'})
data_4 = data_4[data_4['see'] !=1]
data_4

see
passport_number unit_number     
1210425         0              2
1210930         1              2

In [30]:
# Выведем заданные в задаче ситуации: телевизор фактически включён, респондент по данным опроса в комнате
# с включенным телевизором, регистрации нет. При этом только в двух вышеуказанных ДХ одновременно есть другие респонденты
# с регистрацией на этом телевизоре. 
final_situations = data_3[((data_3['passport_number'] == 1210425) | (data_3['passport_number'] == 1210930))\
            & ((data_3['device_state'] == 'ON') & (data_3['display'] == 'в комнате') & (data_3['tv_state'] == 'включён')\
            & (data_3['see'] == 'нет регистрации'))].reset_index(drop=True)
final_situations

code  passport_number button tv_state  unit_number              see  \
0   258124          1210425      Б  включён            0  нет регистрации   
1   258124          1210425      Б  включён            0  нет регистрации   
2   258124          1210425      Б  включён            0  нет регистрации   
3   258124          1210425      Б  включён            0  нет регистрации   
4   258124          1210425      Б  включён            0  нет регистрации   
..     ...              ...    ...      ...          ...              ...   
56  258128          1210930      Б  включён            1  нет регистрации   
57  258128          1210930      Б  включён            1  нет регистрации   
58  258128          1210930      Б  включён            1  нет регистрации   
59  258128          1210930      Б  включён            1  нет регистрации   
60  258128          1210930      Б  включён            1  нет регистрации   

      display  people_cnt        survey_start       survey_finish  \
0   в комнате           2 2022-07-02 17:57:43 2022-07-02 18:07:25   
1   в комнате           2 2022-07-02 17:57:43 2022-07-02 18:07:25   
2   в комнате           2 2022-07-02 17:57:43 2022-07-02 18:07:25   
3   в комнате           2 2022-07-02 17:57:43 2022-07-02 18:07:25   
4   в комнате           2 2022-07-02 17:57:43 2022-07-02 18:07:25   
..        ...         ...                 ...                 ...   
56  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
57  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
58  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
59  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   
60  в комнате           4 2022-07-02 18:52:47 2022-07-02 18:54:12   

   device_state               begin                 end  
0            ON 2022-02-07 09:41:49 2022-02-07 11:31:21  
1            ON 2022-02-07 13:38:42 2022-02-07 14:38:25  
2            ON 2022-02-07 17:01:51 2022-02-07 19:33:01  
3            ON 2022-02-07 21:01:55 2022-02-07 22:12:52  
4            ON 2022-02-07 23:40:16 2022-02-08 00:53:02  
..          ...                 ...                 ...  
56           ON 2022-02-11 20:24:24 2022-02-12 00:19:07  
57           ON 2022-02-13 17:24:44 2022-02-13 19:04:13  
58           ON 2022-02-13 19:04:21 2022-02-13 21:18:43  
59           ON 2022-02-15 14:42:32 2022-02-15 19:38:38  
60           ON 2022-02-15 19:57:20 2022-02-15 23:50:20  

[61 rows x 13 columns]

In [31]:
# Сгруппируем количество ситуаций по размеру ДХ
final_passport_numbers = final_situations.groupby(['passport_number', 'people_cnt']).agg({'code':'count'}).reset_index()
final_passport_numbers.columns = ['passport_number', 'people_cnt', 'situations_cnt']
final_passport_numbers

passport_number  people_cnt  situations_cnt
0          1210425           2              43
1          1210930           4              18

**Вывод:** Выделено два ДХ (1210425 и 1210930), в которых имели место ситуации, когда телевизор фактически включён, респондент по данным опроса в комнате с включенным телевизором, регистрации нет, а у других респондентов регистрация на этом телевизоре есть. Количество таких ситуаций: для 1210425 - 43 ситуаций, для 1210930 - 18 ситуаций.